const http = require('http');
const express = require('express');
const app = express();
app.get("/", (request, response) => {
  console.log(Date.now() + " Ping Received");
  response.sendStatus(200);
});
app.listen(process.env.PORT);
setInterval(() => {
  //http.get(`http://${process.env.PROJECT_DOMAIN}.glitch.me/`);
}, 280000);
//---
//___

const Discord = require("discord.js");
const client = new Discord.Client({ partials: ['USER', 'MESSAGE', 'CHANNEL', 'REACTION'] });
client.lang=1;
//client.SERVER_ID='301063859702071316';
client.SERVER_ID='476431736813912064';


let RH=require(`./raw.js`);
// RH.folder_name='C:/user/discord/bot4/modules';
RH.folder_name=`./modules`;
RH.prefix='!';
//prefix for commands; default value: '!'
RH.log=true;
//true-console log feedback on;false-console log feedback off; default value:'true'
RH.dm_commands=false; 
//true - allowed executing commands sending by DM generated by RH event handler; false - this commands not allowed; default value:false;
RH.fetch_members=false;
RH.fetch_messages=false;
client.on("raw", (...args) => {try{
     RH.run(client,...args);
}catch(err){console.log(err);}; });

client.login(process.env.TOKEN);
//-___

//___
const Discordex = require("discordex.js");
const clientex = new Discordex.Client();
clientex.lang=1;
//clientex.SERVER_ID='301063859702071316';
clientex.SERVER_ID='476431736813912064';

let RHex=require(`./raw_ex.js`);
// RH.folder_name='C:/user/discord/bot4/modules';
RHex.folder_name=`./modules_ex`;
RHex.prefix='!';
//prefix for commands; default value: '!'
RHex.log=true;
//true-console log feedback on;false-console log feedback off; default value:'true'
RHex.dm_commands=false; 
//true - allowed executing commands sending by DM generated by RH event handler; false - this commands not allowed; default value:false;
RHex.fetch_members=false;
RHex.fetch_messages=false;
clientex.on("raw", (...args) => {try{
     RHex.run(clientex,...args);
}catch(err){console.log(err);}; });

//clientex.login(process.env.TOKEN);
//-___